#!/bin/ksh

daemon="/usr/local/bin/obsd-prom-exporter"
daemon_user="_promexp"
daemon_flags="-l /var/log/prom-exporter.log"

. /etc/rc.d/rc.subr

pexp="obsd-prom-export"
rc_reload=NO

rc_pre() {
  touch /var/log/prom-exporter.log
  chown _promexp /var/log/prom-exporter.log
}

rc_cmd $1
